import LeanTra.Algebra.InvolutiveQuantale
import LeanTra.Algebra.KleeneStar
import LeanTra.Algebra.Diamond
import LeanTra.TRA.Basic
import LeanTra.TRA.Howe
import LeanTra.TRA.Modality
import LeanTra.TRA.OperationalDecomposition
import LeanTra.Metatheory.GentzenPrinciples
import LeanTra.Metatheory.Determinism.Evaluation
import LeanTra.Metatheory.Determinism.BigStep
import LeanTra.Metatheory.Confluence.ParallelReduction
import LeanTra.Metatheory.Confluence.Orthogonal
import LeanTra.Metatheory.Confluence.Local
import LeanTra.Instances.PeanoArithmetic
import LeanTra.Instances.Consistency
import LeanTra.Instances.LambdaCalculus
