import LeanTra.Algebra.InvolutiveQuantale
import LeanTra.Algebra.KleeneStar
import LeanTra.SRA.Basic
import LeanTra.SRA.Howe
import LeanTra.SRA.Modality
import LeanTra.SRA.OperationalDecomposition
import LeanTra.Metatheory.GentzenPrinciples
import LeanTra.Metatheory.Evaluation
import LeanTra.Algebra.Diamond
import LeanTra.Metatheory.Confluence.ParallelReduction
import LeanTra.Metatheory.Confluence.Orthogonal
import LeanTra.Metatheory.Confluence.Local
import LeanTra.Instances.FirstOrder.Terms
import LeanTra.Instances.FirstOrder.Relations
import LeanTra.Instances.FirstOrder.SRA
import LeanTra.Instances.FirstOrder.Confluence
import LeanTra.Instances.Toy
import LeanTra.Instances.SecondOrder.Lambda
